name: HourlyReward
version: 1.0.0
author: CyRien
description: Reward your players for each our hour they spend playing.

main: us.cyrien.hr.HourlyReward

permission:
    hourlyreward.reload:
        description: Reload HourlyReward's configuration.
        default: op